before_commands:
    - 'composer install --no-dev --prefer-source'

tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit -c tests/
    php_cpd:
        enabled: true
        excluded_dirs: ['data', 'demo', 'tests', 'vendor']
    php_pdepend:
        enabled: true
        excluded_dirs: ['data', 'demo', 'tests', 'vendor']
    php_analyzer:
        enabled: true
        filter:
            paths: ['src/*', 'tests/*']
    php_mess_detector:
        enabled: true
        filter:
            paths: ['src/*']
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ['src/*', 'tests/*']
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ['src/*', 'tests/*']
    sensiolabs_security_checker: true