<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RbCommentTest\Controller\CommentControllerTest'  => __DIR__ . '/tests/RbCommentTest/Controller/CommentControllerTest.php',
  'RbCommentTest\Controller\ConsoleControllerTest'  => __DIR__ . '/tests/RbCommentTest/Controller/ConsoleControllerTest.php',
  'RbCommentTest\Form\CommentFormTest'              => __DIR__ . '/tests/RbCommentTest/Form/CommentFormTest.php',
  'RbCommentTest\Model\CommentTableTest'            => __DIR__ . '/tests/RbCommentTest/Model/CommentTableTest.php',
  'RbCommentTest\Model\CommentTest'                 => __DIR__ . '/tests/RbCommentTest/Model/CommentTest.php',
  'RbCommentTest\Mvc\Controller\Plugin\CommentTest' => __DIR__ . '/tests/RbCommentTest/View/Helper/CommentTest.php',
  'RbCommentTest\Mvc\Controller\Plugin\MailerTest'  => __DIR__ . '/tests/RbCommentTest/Mvc/Controller/Plugin/MailerTest.php',
  'RbComment\Controller\CommentController'          => __DIR__ . '/src/RbComment/Controller/CommentController.php',
  'RbComment\Controller\ConsoleController'          => __DIR__ . '/src/RbComment/Controller/ConsoleController.php',
  'RbComment\Form\CommentForm'                      => __DIR__ . '/src/RbComment/Form/CommentForm.php',
  'RbComment\Model\Comment'                         => __DIR__ . '/src/RbComment/Model/Comment.php',
  'RbComment\Model\CommentTable'                    => __DIR__ . '/src/RbComment/Model/CommentTable.php',
  'RbComment\Module'                                => __DIR__ . '/Module.php',
  'RbComment\Mvc\Controller\Plugin\Mailer'          => __DIR__ . '/src/RbComment/Mvc/Controller/Plugin/Mailer.php',
  'RbComment\View\Helper\Comment'                   => __DIR__ . '/src/RbComment/View/Helper/Comment.php',
);
