<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RbComment\Controller\CommentController' => __DIR__ . '/src/RbComment/Controller/CommentController.php',
  'RbComment\Form\CommentForm'             => __DIR__ . '/src/RbComment/Form/CommentForm.php',
  'RbComment\Model\Comment'                => __DIR__ . '/src/RbComment/Model/Comment.php',
  'RbComment\Model\CommentTable'           => __DIR__ . '/src/RbComment/Model/CommentTable.php',
  'RbComment\Module'                       => __DIR__ . '/Module.php',
);
