<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RbCommentTest\Model\CommentTest'        => __DIR__ . '/tests/RbCommentTest/Model/CommentTest.php',
  'RbComment\Controller\CommentController' => __DIR__ . '/src/RbComment/Controller/CommentController.php',
  'RbComment\Form\CommentForm'             => __DIR__ . '/src/RbComment/Form/CommentForm.php',
  'RbComment\Model\Comment'                => __DIR__ . '/src/RbComment/Model/Comment.php',
  'RbComment\Model\CommentTable'           => __DIR__ . '/src/RbComment/Model/CommentTable.php',
  'RbComment\Module'                       => __DIR__ . '/Module.php',
  'RbComment\Mvc\Controller\Plugin\Mailer' => __DIR__ . '/src/RbComment/Mvc/Controller/Plugin/Mailer.php',
  'RbComment\View\Helper\Comment'          => __DIR__ . '/src/RbComment/View/Helper/Comment.php',
);
